from finches import Mpipi_frontend
import numpy as np


a1_seqs = ['GSMASASSSQRGRSGSGNSGGGRGGGFGGNDNSGRGGNSSGRGGFGGSRGGGGSGGSGDGYNGSGNDGSNSGGGGSSNDFGNSNNQSSNSGPMKGGNFGGRSSGGSGGGGQYSAKPRNQGGSGGSSSSSSSGSGRRS',
'GSMASASSSQRGRSGSGNSGGGRGGGFGGNDNFGRGGNSSGRGGFGGSRGGGGYGGSGDGYNGFGNDGSNSGGGGSSNDFGNYNNQSSNFGPMKGGNFGGRSSGGSGGGGQYSAKPRNQGGYGGSSSSSSSGSGRRF',
'GSMASASSSQRGRSGSGNFGGGRGGGFGGNDNFGRGGNFSGRGGFGGSRGGGGYGGSGDGYNGFGNDGSNFGGGGSYNDFGNYNNQSSNFGPMKGGNFGGRSSGGSGGGGQYFAKPRNQGGYGGSSSSSSYGSGRRF',
'GSMAFASSFQRGRYGSGNFGGGRGGGFGGNDNFGRGGNFSGRGGFGGSRGGGGYGGSGDGYNGFGNDGSNFGGGGSYNDFGNYNNQSSNFGPMKGGNFGGRSSGGSYGGGQYFAKPRNQGGYGGSSFSSSYGSGRRF',]

mf = Mpipi_frontend()
a1_eps = [-3.9062217543357676, -7.745435983117304, -11.0394544961445, -13.741610868754051]

def test_epsilon():

    for s in a1_seqs:
        assert np.isclose(mf.epsilon(s,s), a1_eps[a1_seqs.index(s)], atol=1e-5)



